### ISSUE TITLE
相同配置，启动后黑屏

### ISSUE THREAD

**Issue by zkzhao** [bk1012/Hackintosh_ASUS-B460M-PLUS_i5-10400#1]
opencore: 0.78
硬件相同，替换了EFI后，启动进入时黑屏，如何解决呢？

**Comment by zkzhao** [comment]
是因为  DP 或者 HDMI 的问题吗？

**Comment by bk1012** [comment]
没有任何报错信息的话，我也不知道怎么解决

黑苹果各种乱七八糟的问题，我当初因为下载和安装系统镜像的时候有插两根内存条就导致安装完全失败

**Comment by bk1012** [comment]
不确认你现在安装是走到哪一步了

你安装黑果小兵的镜像可以正常开机么？（小兵的镜像安装成功以后是可以开机的，只是显卡挂不上去）如果这一步都不行的话可以检查下系统安装步骤及镜像，先把系统安装成功以后再考虑替换 EFI

如果可以正常开机但替换这个 EFI 后黑屏，可以开一下调试模式看下报错。线的影响应该不大，目前我用的是 DP 线，但在我上一份适配了 openCore 0.7.4 的版本用的是 HDMI 

还有需要去确认下系统版本，目前我自用的 12.1 跟 12.2.1 这两个系统版本这份 EFI 都可以使用，但系统升级至 12.3 后黑屏

**Comment by zkzhao** [comment]
> 不确认你现在安装是走到哪一步了
> 
> 你安装黑果小兵的镜像可以正常开机么？（小兵的镜像安装成功以后是可以开机的，只是显卡挂不上去）如果这一步都不行的话可以检查下系统安装步骤及镜像，先把系统安装成功以后再考虑替换 EFI
> 
> 如果可以正常开机但替换这个 EFI 后黑屏，可以开一下调试模式看下报错。线的影响应该不大，目前我用的是 DP 线，但在我上一份适配了 openCore 0.7.4 的版本用的是 HDMI
> 
> 还有需要去确认下系统版本，目前我自用的 12.1 跟 12.2.1 这两个系统版本这份 EFI 都可以使用，但系统升级至 12.3 后黑屏


感谢回复！

安装黑果小兵的镜像可以正常开机，替换这个 EFI 后黑屏。系统是12.2.1、12.3 都有尝试。
开调试模式看报错信息的方法是？在boot-args上加-v 吗？ 等看到报错信息后再来。

另外确认一下，是10400核显驱动吗？

**Comment by bk1012** [comment]
嗯，我是10400核显，没单独配显卡

好像是这么加的，不过看到报错信息以后你可以先谷歌一下，我这份 EFI 配置好以后替换上去就没出过问题，所以对于报错我也没啥相关经验

**Comment by zkzhao** [comment]
谢谢帮助！
