### ISSUE TITLE
大神有没有适配13的计划

### ISSUE THREAD

**Issue by zhaoest** [bk1012/Hackintosh_ASUS-B460M-PLUS_i5-10400#3]
RT

**Comment by bk1012** [comment]
这玩意升级一次也折腾的，我通常几个月升级一次。上一次升级才不到一个月，短期内不会再折腾了

**Comment by zhaoest** [comment]
哈哈，太有缘分了，我5号刚买个渣渣5600xt，你6号就更新了，666

<img width="495" alt="image" src="https://user-images.githubusercontent.com/7814448/211238889-c769ebd8-61d1-4ca9-9999-eb5729cd6390.png">
